{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "n8n.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "n8n.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: {{ include "n8n.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  policyTypes: [Ingress, Egress]
  ingress:
    - from: []
      ports:
        - protocol: TCP
          port: {{ .Values.service.port }}
  egress:
    - to: []
      ports:
        - protocol: TCP
          port: 5432   # Postgres
        - protocol: TCP
          port: 6379   # Redis
{{- end }}
