{{- if and .Values.taskRunners.enabled (not .Values.taskRunners.authToken.existingSecret) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "n8n.fullname" . }}-task-runners
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "n8n.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.taskRunners.authToken.value }}
  N8N_RUNNERS_AUTH_TOKEN: {{ .Values.taskRunners.authToken.value | b64enc | quote }}
  {{- else }}
  {{- /* Generate a random token if none provided */}}
  N8N_RUNNERS_AUTH_TOKEN: {{ randAlphaNum 32 | b64enc | quote }}
  {{- end }}
{{- end }}
