name: Release Please

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write
  id-token: write
  actions: read
  packages: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    outputs:
      release_created: ${{ steps.check.outputs.release_created }}
      tag_name: ${{ steps.check.outputs.tag_name }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check if release needed
        id: check
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Get the latest tag
          LATEST_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "v0.0.0")
          echo "Latest tag: $LATEST_TAG"

          # Get current version from manifest
          CURRENT_VERSION=$(jq -r '."."' .release-please-manifest.json)
          echo "Current version: $CURRENT_VERSION"

          # Check if we need a release
          if [ "$LATEST_TAG" != "v$CURRENT_VERSION" ]; then
            echo "release_created=true" >> $GITHUB_OUTPUT
            echo "tag_name=v$CURRENT_VERSION" >> $GITHUB_OUTPUT

            # Create release as draft using gh CLI
            gh release create "v$CURRENT_VERSION" \
              --title "$CURRENT_VERSION" \
              --notes "Release $CURRENT_VERSION" \
              --draft \
              --repo "$GITHUB_REPOSITORY"

            echo "✅ Created release v$CURRENT_VERSION"
          else
            echo "release_created=false" >> $GITHUB_OUTPUT
            echo "No new release needed"
          fi

  publish:
    runs-on: ubuntu-latest
    needs: release-please
    if: ${{ needs.release-please.outputs.release_created }}
    outputs:
      hashes: ${{ steps.hash.outputs.hashes }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
          version: '3.12.1'

      - name: Update Chart Version
        run: |
          # Extract version from tag (remove 'v' prefix)
          CHART_VERSION="${{ needs.release-please.outputs.tag_name }}"
          CHART_VERSION="${CHART_VERSION#v}"
          sed -i "s/^version:.*/version: $CHART_VERSION/" charts/n8n-app/Chart.yaml
          
          echo "Updated chart version to: $CHART_VERSION"

      - name: Package Chart
        run: |
          helm package charts/n8n-app --destination ./charts/

      - name: Generate hashes
        shell: bash
        id: hash
        run: |
          echo "hashes=$(sha256sum charts/*.tgz | base64 -w0)" >> "$GITHUB_OUTPUT"

      - name: Upload Release Assets
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release upload ${{ needs.release-please.outputs.tag_name }} charts/*.tgz --clobber

      - name: Log in to Docker Hub
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
        run: |
          if [ -z "$DOCKERHUB_USERNAME" ] || [ -z "$DOCKERHUB_TOKEN" ]; then
            echo "❌ DOCKERHUB_USERNAME or DOCKERHUB_TOKEN secrets not set"
            exit 1
          fi
          echo "$DOCKERHUB_TOKEN" | helm registry login registry-1.docker.io -u "$DOCKERHUB_USERNAME" --password-stdin

      - name: Push chart to Docker Hub OCI
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
        run: |
          CHART_NAME=$(helm show chart charts/n8n-app | awk '/^name:/{print $2}')
          CHART_VERSION=$(helm show chart charts/n8n-app | awk '/^version:/{print $2}')
          helm push "charts/${CHART_NAME}-${CHART_VERSION}.tgz" "oci://registry-1.docker.io/${DOCKERHUB_USERNAME}"
          echo "✅ Chart published: oci://registry-1.docker.io/${DOCKERHUB_USERNAME}/${CHART_NAME}:${CHART_VERSION}"
          echo "🔗 Docker Hub repo: https://hub.docker.com/repository/docker/${DOCKERHUB_USERNAME}/${CHART_NAME}/general"

      - name: Install ORAS
        uses: oras-project/setup-oras@v1
        with:
          version: 1.0.0

      - name: Install Cosign
        uses: sigstore/cosign-installer@v3
        with:
          cosign-release: 'v2.2.4'

      - name: Tag Helm chart as :latest
        if: ${{ !contains(needs.release-please.outputs.tag_name, '-') }}
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
        run: |
          CHART_NAME=$(helm show chart charts/n8n-app | awk '/^name:/{print $2}')
          CHART_VERSION=$(helm show chart charts/n8n-app | awk '/^version:/{print $2}')
          echo "$DOCKERHUB_TOKEN" | oras login registry-1.docker.io -u "$DOCKERHUB_USERNAME" --password-stdin

          SRC="registry-1.docker.io/${DOCKERHUB_USERNAME}/${CHART_NAME}:${CHART_VERSION}"
          DST="registry-1.docker.io/${DOCKERHUB_USERNAME}/${CHART_NAME}:latest"

          oras copy "${SRC}" "${DST}"
          echo "🔖 Tagged ${SRC} as ${DST}"

      - name: Sign Helm chart with Cosign
        env:
          COSIGN_EXPERIMENTAL: 1
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
        run: |
          CHART_NAME=$(helm show chart charts/n8n-app | awk '/^name:/{print $2}')
          CHART_VERSION=$(helm show chart charts/n8n-app | awk '/^version:/{print $2}')

          # Sign the chart artifact
          cosign sign --yes "registry-1.docker.io/${DOCKERHUB_USERNAME}/${CHART_NAME}:${CHART_VERSION}"

          # Sign the latest tag if this is not a pre-release
          if [[ ! "${{ needs.release-please.outputs.tag_name }}" =~ "-" ]]; then
            cosign sign --yes "registry-1.docker.io/${DOCKERHUB_USERNAME}/${CHART_NAME}:latest"
          fi

          echo "🔐 Chart artifacts signed with Cosign"

      - name: Publish Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release edit ${{ needs.release-please.outputs.tag_name }} --draft=false
          echo "📦 Release ${{ needs.release-please.outputs.tag_name }} published"

  # SLSA provenance generation as separate job
  provenance:
    needs: [release-please, publish]
    if: ${{ needs.release-please.outputs.release_created }}
    permissions:
      actions: read
      id-token: write
      contents: write
    uses: slsa-framework/slsa-github-generator/.github/workflows/generator_generic_slsa3.yml@v1.10.0
    with:
      base64-subjects: ${{ needs.publish.outputs.hashes }}
      provenance-name: "n8n-helm-chart.intoto.jsonl"

  upload-provenance:
    runs-on: ubuntu-latest
    needs: [release-please, provenance]
    if: ${{ needs.release-please.outputs.release_created }}
    steps:
      - name: Download provenance
        uses: actions/download-artifact@v4
        with:
          name: n8n-helm-chart.intoto.jsonl

      - name: Upload provenance to release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release upload ${{ needs.release-please.outputs.tag_name }} n8n-helm-chart.intoto.jsonl --clobber
