name: Release Please

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
      tag_name: ${{ steps.release.outputs.tag_name }}
    steps:
      - name: Release Please
        id: release
        uses: googleapis/release-please-action@v4
        with:
          config-file: release-please-config.json
          manifest-file: .release-please-manifest.json

  publish:
    runs-on: ubuntu-latest
    needs: release-please
    if: ${{ needs.release-please.outputs.release_created }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
          version: '3.12.1'

      - name: Update Chart Version
        run: |
          # Extract version from tag (remove 'v' prefix)
          CHART_VERSION="${{ needs.release-please.outputs.tag_name }}"
          CHART_VERSION="${CHART_VERSION#v}"
          
          # Update Chart.yaml version
          sed -i "s/^version:.*/version: $CHART_VERSION/" charts/n8n-app/Chart.yaml
          
          echo "Updated chart version to: $CHART_VERSION"

      - name: Package Chart
        run: |
          helm package charts/n8n-app --destination ./charts/

      - name: Upload Release Assets
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release upload ${{ needs.release-please.outputs.tag_name }} charts/*.tgz --clobber

      - name: Log in to Docker Hub
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
        run: |
          if [ -z "$DOCKERHUB_USERNAME" ] || [ -z "$DOCKERHUB_TOKEN" ]; then
            echo "❌ DOCKERHUB_USERNAME or DOCKERHUB_TOKEN secrets not set"
            exit 1
          fi
          echo "$DOCKERHUB_TOKEN" | helm registry login registry-1.docker.io -u "$DOCKERHUB_USERNAME" --password-stdin

      - name: Push to Docker Hub OCI Registry
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
        run: |
          CHART_NAME=$(helm show chart charts/n8n-app | grep '^name:' | cut -d' ' -f2)
          CHART_VERSION=$(helm show chart charts/n8n-app | grep '^version:' | cut -d' ' -f2)
          
          helm push charts/${CHART_NAME}-${CHART_VERSION}.tgz oci://registry-1.docker.io/$DOCKERHUB_USERNAME
          
          helm package charts/n8n-app --version latest --destination ./charts/
          helm push charts/${CHART_NAME}-latest.tgz oci://registry-1.docker.io/$DOCKERHUB_USERNAME
          
          echo "✅ Chart published with version tags:"
          echo "📦 Specific version: oci://registry-1.docker.io/$DOCKERHUB_USERNAME/${CHART_NAME}:${CHART_VERSION}"
          echo "📦 Latest: oci://registry-1.docker.io/$DOCKERHUB_USERNAME/${CHART_NAME}:latest"
          echo "🔗 Docker Hub: https://hub.docker.com/r/$DOCKERHUB_USERNAME/${CHART_NAME}"